element_type (empty)

element_type (num)
element_type (string)
element_type (functiondef)
element_type (symbol)

element_type (bitsdesc_mpeg2_mnemonic)
element_type (bitsdesc_mpeg2_string)
element_type (bitsdesc_h264)
element_type (h264_func_cat)

element_type (num_range)
element_type (num_or)

element_type (variable)
element_type (variable_array)
element_type (variable_stream)

element_type (arrayindex)
element_type (functioncall)

element_type (pred_def)
element_type (predefined)

/* statements */
element_type (if)
element_type (if_else)
element_type (while)
element_type (dowhile)
element_type (for)
element_type (return)

/* operators */
element_type (assign)
element_type (plusassign)
element_type (logicaland)
element_type (logicalor)
element_type (bitwiseand)
element_type (bitwiseor)
element_type (equal)
element_type (gt)
element_type (ge)
element_type (lt)
element_type (le)
element_type (notequal)
element_type (leftshift)
element_type (rightshift)
element_type (plus)
element_type (minus)
element_type (divide)
element_type (multiply)
element_type (modulo)
element_type (logicalnot)
element_type (plusplus_pre)
element_type (plusplus_post)
element_type (minusminus_pre)
element_type (minusminus_post)
